### ISSUE TITLE
Unexpected token on main.js

### ISSUE THREAD

**Issue by heritechie** [koliseoapi/react-async-autocomplete#4]
ERROR in ./node_modules/react-async-autocomplete/lib/main.js
Module parse failed: ~/.node_modules/react-async-autocomplete/lib/main.js Unexpected token (191:6)
You may need an appropriate loader to handle this file type.
```
const { items, index, isOpen } = this.state;
const $empty = items && items.length? undefined : 
<div className="autocomplete-li empty">{this.props.emptyMessage}</div>;
return !isOpen? undefined : (
<div className="autocomplete-list" onMouseOver={this.onMouseOver}>
```

Here's my relevant package.json:

```
{
  "name": "",
  "version": "1.0.0",
  "description": "## Setup",
  "main": "index.js",
  "dependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "react": "^15.6.1",
    "react-async-autocomplete": "^1.0.3",
    "react-dom": "^15.6.1",
    "react-number-format": "^2.0.4",
    "react-select": "^1.0.0-rc.5",
    "webpack": "^3.5.5"
  },
  "devDependencies": {
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-destructuring": "^6.23.0",
    "css-loader": "^0.28.7"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  
}
```
and webpack.config.js:
```
var webpack = require('webpack')
var path = require('path')

module.exports = {
  entry: {
    app: './kasir_spa/app.js'
  },
  output: {
    filename: 'assets/js/kasir_spa.js',
    sourceMapFilename: 'assets/js/kasir_spa.map'
  },
  devtool: '#source-map',
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['react', 'es2015'],
            plugins: ['transform-class-properties', 'transform-es2015-destructuring']
          }
        }
      }
    ]
  }
}

```
and then running webpack from the command line.

Am I missing something obvious here?

**Comment by icoloma** [comment]
You need to include this `react-async-autocomplete` in your babel compilation. modify your `webpack.config.js` in one of these two ways:

```js
// do not exclude this library from babel processing
exclude: /node_modules\/(?!react-async-autocomplete)/,

// include instead of exclude
include: [ /src\/es6/, /react-async-autocomplete/ ],
//exclude: /node_modules/,
```

**Comment by IronTony** [comment]
Hello @icoloma 

would you be so kind, to write the full version of the object to place in the webpack config please?
Thank you

**Comment by icoloma** [comment]
Following the example above (I removed bower_components for the sake of clarity):

```js
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!react-async-autocomplete)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['react', 'es2015'],
            plugins: ['transform-class-properties', 'transform-es2015-destructuring']
          }
        }
      }
    ]
  }
```

**Comment by aaronleslie** [comment]
solved my problem. Cheers!

**Comment by cullsin** [comment]
Hi, 
I am getting the same error. I am using react create app. I have updated webpack.config.js which is in the react-async-autocomplete folder. Can you please suggest me what is missing ?

![image](https://user-images.githubusercontent.com/5137598/52721953-ba7d7d00-2fd0-11e9-85d0-d39c452f8bd9.png)

**Comment by icoloma** [comment]
@cullsin You still need to transpile `react-async-autocomplete`. By default Babel will not transpile any dependency inside `node_modules`, and you need to override this. That's what the `excludes` line is about, which for babelify is called `ignore` ([see here](https://github.com/babel/babelify)).

**Comment by cullsin** [comment]
sorry, Can you please suggest me how to transpile ?
