### ISSUE TITLE
TypeError: Cannot read property 'oneOfType' of undefined

### ISSUE THREAD

**Issue by IronTony** [koliseoapi/react-async-autocomplete#5]
Hi,
I am using create-react-app ejected, when I install and import your component, I get back the following error:
![untitled-1](https://user-images.githubusercontent.com/3645225/31044066-201700ee-a5c8-11e7-83c3-a53984f847dd.jpg)
Any hint, I really wanna use your module.
Thank you in advance

**Comment by icoloma** [comment]
Please review the version of React that you are using. It seems that the line `import PropTypes from 'prop-types'` is returning undefined. Maybe you don't have the library included?
