### ISSUE TITLE
Npm package contains non-transpiled ES6 and React code

### ISSUE THREAD

**Issue by BjarkeNL** [koliseoapi/react-async-autocomplete#6]
Hi. 
Thanks for putting this up.

I haven't yet been able to try it out yet, as the npm package contains ES6 and React code, which haven't been transpiled back to ES5. Perhaps you could put the transpiled code into the npm-repository instead of what is currently there?

**Comment by icoloma** [comment]
We are not providing with a transpiled version by design, since that would require including the whole React library (dependencies would be included as well). Can you elaborate a bit about your use case? Why do you need a transpiled version?

**Comment by BjarkeNL** [comment]
Thank you for the reply! I found a different library, so it's no longer a problem for me, but to explain:

The reason i wished to have an ES5 version, was that it didn't work in browsers, without transpiling the library (inside node_modules) myself. On the client-side, i'm using webpack, and currently i'm excluding everything in node_modules from being transpiled, and i would like to keep it that way :)

Also, it didn't work on the node-server with server-side rendering, since node doesn't support the react-syntax and since i don't transpile code inside node_modules server-side either.

I'm no expert at all (i've never released an npm package), but it seems other react libraries are transpiled into ES5 and just depend on the react-library, so it seems to be possible.

Thank you again for the reply :)

**Comment by icoloma** [comment]
We build a ES5 as part of the process to deploy the [demo environment](https://koliseoapi.github.io/react-async-autocomplete/), but chose not to publish it on purpose. Keep in mind that including transpiled libraries will quite likely include multiple versions of React, and in general you may not want to continue transpiling forever [depending on your browser requirements](https://medium.freecodecamp.org/you-might-not-need-to-transpile-your-javascript-4d5e0a438ca).
