### ISSUE TITLE
cannot load the module properly

### ISSUE THREAD

**Issue by aaronleslie** [koliseoapi/react-async-autocomplete#7]
[https://image.prntscr.com/image/eV9VsWIeQbmQHojOtjmdpg.png](url),

I'm using create-react-app and load the module properly.

```
import Autocomplete from "react-async-autocomplete";
```

I try to copy the whole main.js to https://babeljs.io/repl/ and compile with stage-0 and it works.

what should I do in config in create-react-app to bypass this issue?

**Comment by icoloma** [comment]
Hi Aaron, can you please paste here your error message?

**Comment by aaronleslie** [comment]
pls refer to below url.
https://image.prntscr.com/image/eV9VsWIeQbmQHojOtjmdpg.png

**Comment by icoloma** [comment]
You need to configure your environment to also transpile dependencies, not just your source code

This seems like a duplicate of #4. Closing as duplicate, please reopen if it's not.
